AWSTemplateFormatVersion: "2010-09-09"

Resources:
    DeployerRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Principal:
                  AWS:
                    - !Sub 'arn:aws:iam::${AWS::AccountId}:user/keymanager-dev'
                Action: sts:AssumeRole
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
          Policies:
            - PolicyName: ServerlessFrameworkCli
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Sid: ValidateCloudFormation
                    Effect: Allow
                    Action:
                      - cloudformation:ValidateTemplate
                    Resource: '*'
                  - Sid: ExecuteCloudFormation
                    Effect: Allow
                    Action:
                      - cloudformation:CreateChangeSet
                      - cloudformation:CreateStack
                      - cloudformation:DeleteChangeSet
                      - cloudformation:DeleteStack
                      - cloudformation:DescribeChangeSet
                      - cloudformation:DescribeStackEvents
                      - cloudformation:DescribeStackResource
                      - cloudformation:DescribeStackResources
                      - cloudformation:DescribeStacks
                      - cloudformation:ExecuteChangeSet
                      - cloudformation:ListStackResources
                      - cloudformation:SetStackPolicy
                      - cloudformation:UpdateStack
                      - cloudformation:UpdateTerminationProtection
                      - cloudformation:GetTemplate
                    Resource:
                      - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/example-project-*/*'
                      - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/campaigns-module-hg-*/*'
                  - Sid: ReadLambda
                    Effect: Allow
                    Action:
                      - lambda:Get*
                      - lambda:List*
                      - lambda:PublishLayerVersion
                      - lambda:DeleteLayerVersion
                      - lambda:CreateEventSourceMapping
                    Resource:
                      - '*'
                  - Sid: ManageSlsDeploymentBucket
                    Effect: Allow
                    Action:
                      - s3:CreateBucket
                      - s3:DeleteBucket
                      - s3:ListBucket
                      - s3:PutObject
                      - s3:GetObject
                      - s3:DeleteObject
                      - s3:GetBucketPolicy
                      - s3:PutBucketPolicy
                      - s3:DeleteBucketPolicy
                      - s3:PutBucketAcl
                      - s3:GetEncryptionConfiguration
                      - s3:PutEncryptionConfiguration
                    Resource:
                      - !Sub 'arn:aws:s3:::s3-*'
                  - Sid: ListS3
                    Effect: Allow
                    Action:
                      - s3:List*
                    Resource: '*'
            - PolicyName: DeployLambdaFunctions
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - lambda:Get*
                      - lambda:List*
                      - lambda:CreateFunction
                      - lambda:DeleteFunction
                      - lambda:CreateFunction
                      - lambda:DeleteFunction
                      - lambda:UpdateFunctionConfiguration
                      - lambda:UpdateFunctionCode
                      - lambda:PublishVersion
                      - lambda:CreateAlias
                      - lambda:DeleteAlias
                      - lambda:UpdateAlias
                      - lambda:AddPermission
                      - lambda:RemovePermission
                      - lambda:InvokeFunction
                      - lambda:TagResource
                      - lambda:PublishLayerVersion
                      - lambda:DeleteLayerVersion
                      - lambda:PutFunctionConcurrency
                    Resource:
                      - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:example-project-*'
                      - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:campaigns-module-hg-*'
            - PolicyName: DeployLogGroups
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - logs:CreateLogGroup
                      - logs:Get*
                      - logs:Describe*
                      - logs:List*
                      - logs:DeleteLogGroup
                      - logs:PutResourcePolicy
                      - logs:DeleteResourcePolicy
                      - logs:PutRetentionPolicy
                      - logs:DeleteRetentionPolicy
                      - logs:TagLogGroup
                      - logs:UntagLogGroup
                    Resource:
                      - "*"
                  - Effect: Allow
                    Action:
                      - logs:Describe*
                    Resource:
                      - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'
                  - Effect: Allow
                    Action:
                      - logs:CreateLogDelivery
                      - logs:DeleteLogDelivery
                      - logs:DescribeResourcePolicies
                      - logs:DescribeLogGroups
                    Resource:
                      - '*'
            - PolicyName: DeployAppBuckets
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Sid: AllBucketPermissions
                    Effect: Allow
                    Action:
                      - s3:ListAllMyBuckets
                      - s3:ListBucket
                    Resource: '*'
                  - Sid: WriteAppBuckets
                    Effect: Allow
                    Action:
                      - s3:Get*
                      - s3:List*
                      - s3:CreateBucket
                      - s3:DeleteBucket
                      - s3:PutObject
                      - s3:DeleteObject
                      - s3:PutBucketPolicy
                      - s3:DeleteBucketPolicy
                      - s3:PutEncryptionConfiguration
                      - s3:PutBucketPublicAccessBlock
                    Resource:
                      - !Sub 'arn:aws:s3:::*'
            - PolicyName: DeployCloudFront
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - cloudfront:Get*
                      - cloudfront:List*
                      - cloudfront:CreateDistribution
                      - cloudfront:UpdateDistribution
                      - cloudfront:DeleteDistribution
                      - cloudfront:TagResource
                      - cloudfront:UntagResource
                    Resource:
                      - !Sub 'arn:aws:cloudfront::${AWS::AccountId}:*/*'
                  - Sid: DeployCloudFrontOriginAccessIdentity
                    Effect: Allow
                    Action:
                      - cloudfront:CreateCloudFrontOriginAccessIdentity
                      - cloudfront:UpdateCloudFrontOriginAccessIdentity
                      - cloudfront:GetCloudFrontOriginAccessIdentity
                      - cloudfront:GetCloudFrontOriginAccessIdentityConfig
                      - cloudfront:DeleteCloudFrontOriginAccessIdentity
                      - cloudfront:ListCloudFrontOriginAccessIdentities
                    Resource: '*'
            - PolicyName: DeployLambdaExecutionRoles
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - iam:Get*
                      - iam:List*
                      - iam:PassRole
                      - iam:CreateRole
                      - iam:DeleteRole
                      - iam:AttachRolePolicy
                      - iam:DeleteRolePolicy
                      - iam:PutRolePolicy
                      - iam:TagRole
                      - iam:UntagRole
                      - iam:GetRole
                      - dynamodb:DeleteItem
                      - dynamodb:UpdateItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:Query
                    Resource:
                      - !Sub 'arn:aws:iam::${AWS::AccountId}:role/campaigns-module-hg-*'
                      - !Sub 'arn:aws:iam::${AWS::AccountId}:role/campaigns-module-hg-*/*'
            - PolicyName: DeployAPIGateway
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - apigateway:GET
                      - apigateway:POST
                      - apigateway:PUT
                      - apigateway:PATCH
                      - apigateway:DELETE
                    Resource:
                      - "*"
            - PolicyName: DeployEventBridge
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - events:Describe*
                      - events:Get*
                      - events:List*
                      - events:CreateEventBus
                      - events:DeleteEventBus
                      - events:PutRule
                      - events:DeleteRule
                      - events:PutTargets
                      - events:RemoveTargets
                      - events:TagResource
                      - events:UntagResource
                    Resource:
                      - !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/example-project-*'
                      - !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/example-project-*'
                      - !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/campaigns-module-hg-*'
                      - !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/campaigns-module-hg-*'
            - PolicyName: DeploySNSTopics
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - sns:Get*
                      - sns:Describe*
                      - sns:CreateTopic
                      - sns:DeleteTopic
                      - sns:SetTopicAttributes
                      - sns:Subscribe
                      - sns:Unsubscribe
                      - sns:TagResource
                    Resource:
                      - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:example-project-*'
                      - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:campaigns-module-hg-*'
            - PolicyName: DeployDynamoDB
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:CreateTable
                      - dynamodb:CreateTableReplica
                      - dynamodb:CreateGlobalTable
                      - dynamodb:DeleteTable
                      - dynamodb:DeleteGlobalTable
                      - dynamodb:DeleteTableReplica
                      - dynamodb:Describe*
                      - dynamodb:List*
                      - dynamodb:Get*
                      - dynamodb:TagResource
                      - dynamodb:UntagResource
                      - dynamodb:UpdateContinuousBackups
                      - dynamodb:UpdateGlobalTable
                      - dynamodb:UpdateGlobalTableSettings
                      - dynamodb:UpdateTable
                      - dynamodb:UpdateTableReplicaAutoScaling
                      - dynamodb:UpdateTimeToLive
                      - dynamodb:DeleteItem
                      - dynamodb:UpdateItem
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:Query
                    Resource:
                      - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*'
                      - !Sub 'arn:aws:dynamodb::${AWS::AccountId}:global-table/*'
            - PolicyName: DeploySQS
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - sqs:CreateQueue
                      - sqs:DeleteQueue
                      - sqs:SetQueueAttributes
                      - sqs:AddPermission
                      - sqs:RemovePermission
                      - sqs:TagQueue
                      - sqs:UntagQueue
                      - sqs:Get*
                      - sqs:List*
                      - sqs:sendmessage
                    Resource:
                      - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:example-project-*'
                      - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:campaigns-module-hg-*'
            - PolicyName: DeploySSMParameterStore
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - ssm:GetParameter*
                      - ssm:DescribeParameters
                      - ssm:DeleteParameter*
                      - ssm:PutParameter
                    Resource:
                      - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*'
                      - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*/*'
            - PolicyName: ServerlessDomainManagerDeployPolicy
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - apigateway:AddCertificateToDomain
                      - apigateway:RemoveCertificateFromDomain
                    Resource: !Sub arn:aws:apigateway:${AWS::Region}::/domainnames*
                  - Effect: Allow
                    Action:
                      - apigateway:DELETE
                      - apigateway:GET
                      - apigateway:PATCH
                      - apigateway:POST
                    Resource:
                      !Sub arn:aws:apigateway:${AWS::Region}::/apis*
                      !Sub arn:aws:apigateway:${AWS::Region}::/domainnames*
                      !Sub arn:aws:apigateway:${AWS::Region}::/restapis*
                  - Effect: Allow
                    Action:
                      - cloudfront:UpdateDistribution
                    Resource: '*'
                  - Effect: Allow
                    Action:
                      - route53:ListHostedZones
                    Resource: '*'
                  - Effect: Allow
                    Action:
                      - acm:ListCertificates
                      - acm:DescribeCertificate
                    Resource: '*'
                  - Effect: Allow
                    Action:
                      - route53:ChangeResourceRecordSets
                      - route53:GetHostedZone
                      - route53:ListResourceRecordSets
                    Resource: !Sub arn:aws:route53:::hostedzone/*
                  - Effect: Allow
                    Action:
                      - iam:CreateServiceLinkedRole
                    Resource:
                      - !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ops.apigateway.amazonaws.com/AWSServiceRoleForAPIGateway
            - PolicyName: ServerlessCognitoDeployPolicy
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - cognito-idp:CreateUserPool
                      - cognito-idp:CreateUserPoolClient
                      - cognito-idp:DeleteUserPoolClient
                      - cognito-idp:DeleteUserPool
                      - cognito-idp:AdminCreateUser
                      - cognito-idp:AdminInitiateAuth
                      - cognito-idp:AdminSetUserPassword
                    Resource: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*
                  

